### ISSUE TITLE
Segfault for ODD+Pythia8+Geant4

### ISSUE THREAD

**Issue by andiwand** [acts-project/acts#1578] opened 2022-10-06 10:06 UTC
@benjaminhuth pointed out that ODD+Pythia8+Geant4 will segfault in full chain

I just verified this. See attached files for more information.

[segfault.txt](https://github.com/acts-project/acts/files/9723819/segfault.txt)
[full_chain.txt](https://github.com/acts-project/acts/files/9723821/full_chain.txt)

**Comment by paulgessinger** [comment] 2022-10-06 10:30
Hm, could be the two interfere?

**Comment by asalzburger** [comment] 2022-10-06 10:35
Is this executed in single thread ?

**Comment by asalzburger** [comment] 2022-10-06 10:36
No good ``numThreads=-1`` - this would need Geant4MT.

**Comment by benjaminhuth** [comment] 2022-10-06 10:47
For me this crashes with one thread as well

**Comment by asalzburger** [comment] 2022-10-06 10:51
Is that with the same error / segfault ?

**Comment by benjaminhuth** [comment] 2022-10-06 11:09
Hmm it looks a bit different to be honest, but couldn't check in detail for no.
I attache my gdb backtrace, maybe this gives a hint.

[backtrace.txt](https://github.com/acts-project/acts/files/9724203/backtrace.txt)

**Comment by Corentin-Allaire** [comment] 2022-10-11 16:42
As we discussed during today's meeting I tried to replace the ODD by the GDLM implementation of Alice_v3 and it ran through with just a few warning.
So the issue is either with the ODD itself or the ```DDG4DetectorConstruction```...

**Comment by Corentin-Allaire** [comment] 2022-11-23 17:13
I have had an other look at this and I just notice something. If I start removing the support from the ODD xml the segfault happen much later so maybe there is something bad with the support surface definition ?

**Comment by paulgessinger** [comment] 2023-01-20 08:57
For sure this is something that we need to fix.

**Comment by benjaminhuth** [comment] 2023-01-20 11:37
Okay, I have investigated this a bit and some new infos:

First of all, I enabled some logging facilities in Geant4, which gave me the result that this is caused by photons quite far away from the center in z direction (z is around 1e4):
![image](https://user-images.githubusercontent.com/37871400/213686049-a80ebfae-57ad-4931-a7aa-393a16dee381.png)

Then I also could reproduce the crash with the `ParticleGun`:

![image](https://user-images.githubusercontent.com/37871400/213686355-0a5115b7-8ecd-4f36-82f4-9c926d6e4564.png)

I'm not totally sure what to do with these information, but maybe someone has an idea :)

**Comment by paulgessinger** [comment] 2023-01-20 11:48
So it's G4 breaking in a specific region of the detector?

**Comment by Corentin-Allaire** [comment] 2023-01-20 12:45
Wait the energy goes to 0 in the second step. Could it be that G4 doesn't handle photon stopping in some volumes ?

**Comment by benjaminhuth** [comment] 2023-01-20 12:49
> Wait the energy goes to 0 in the second step. Could it be that G4 doesn't handle photon stopping in some volumes ?

No I think with the electron in the pixel endcap is everythin fine, the photon below is the problem. There it only loggs the 0th step and then breaks.

I could imagine that a problem is that it starts already outside of the detector (in the `world_volume_1`)?

**Comment by Corentin-Allaire** [comment] 2023-01-20 13:14
Oh yeah I was looking at the wrong line... But you are right, the world volume size is 10m along z so this photon is outside the DD4Hep detector.

**Comment by Corentin-Allaire** [comment] 2023-01-20 15:05
Unfortunately, I don't think this is the only issue :(
I tried to edit the particle selector to remove all particle with x, y or z larger than 5m (in abs) and it still crashes with ttbar. How did you get those extra log Benjamin ?

**Comment by benjaminhuth** [comment] 2023-01-20 15:08
Allready merged: https://github.com/acts-project/acts/pull/1790

**Comment by Corentin-Allaire** [comment] 2023-01-20 15:12
Oh perfect I will have a look next week in more detail then !

**Comment by benjaminhuth** [comment] 2023-01-23 10:57
> Unfortunately, I don't think this is the only issue :( I tried to edit the particle selector to remove all particle with x, y or z larger than 5m (in abs) and it still crashes with ttbar. How did you get those extra log Benjamin ?

Actually I was able to run one event in the pythia8+geant4+ODD combination without segfault by increasing the world volumen manually from `10m` to `100m` in the ODD xml files...

I'm not sure if something like that would be a reasonable fix? Has this any other implications @asalzburger ?

I will try to run more events now, however, they take quite a long time (around 30 minutes per event)

**Comment by benjaminhuth** [comment] 2023-01-23 12:21
> I will try to run more events now, however, they take quite a long time (around 30 minutes per event)

Okay, actually it does not resolve the issue, I still get the segfault in a later event. Maybe it has just changed the random numbers a bit so that 1 event went through.

**Comment by Corentin-Allaire** [comment] 2023-01-23 12:52
A bit unrelated but there is a bug in 'addGeant4' in 'simulation.py'. Line 597 it uses `particles_input` for the G4 input (instead of `particles_selected`) ignoring the particle selector. I can open a quick MR to fix this

**Comment by Corentin-Allaire** [comment] 2023-01-23 13:14
> A bit unrelated but there is a bug in 'addGeant4' in 'simulation.py'. Line 597 it uses `particles_input` for the G4 input (instead of `particles_selected`) ignoring the particle selector. I can open a quick MR to fix this

If someone wants to have a look : https://github.com/acts-project/acts/pull/1792

**Comment by Corentin-Allaire** [comment] 2023-01-23 13:23
With this you can cut the particle outside the detector by adding `preselectParticles = ParticleSelectorConfig(eta=(-3.0, 3.0),absZmin=(0, 1e4), pt=(150 * u.MeV, None), removeNeutral=True),` to the `addGeant4`. Doesn't solve the segfault in the ttbar case (but solve the photon issue).

**Comment by Corentin-Allaire** [comment] 2023-01-23 14:48
Actually the code seem to be running on my side and doesn't segfault anymore... Can someone else confirm ?

**Comment by andiwand** [comment] 2023-01-24 08:58
@Corentin-Allaire are you using the chain from above? otherwise if you could share the script I can try to verify

**Comment by Corentin-Allaire** [comment] 2023-01-24 09:47
@andiwand here is the chain I use : 
[full_chain_odd.txt](https://github.com/acts-project/acts/files/10488274/full_chain_odd.txt)

**Comment by andiwand** [comment] 2023-01-24 09:56
this is still segfaulting for me

[segfault.txt](https://github.com/acts-project/acts/files/10488343/segfault.txt)

**Comment by Corentin-Allaire** [comment] 2023-01-24 10:01
I might have changed something else by accident let me check (maybe you can also run it with verbose log of G4 ?)

**Comment by andiwand** [comment] 2023-01-24 10:14
did you run geant4 in verbose mode @benjaminhuth ? somehow it runs now for a couple of minutes without crashing

**Comment by benjaminhuth** [comment] 2023-01-24 10:16
nope, at least that last one not.
But I think we must consider the verbose mode to be extreeemly slow due to this huge printouts...

**Comment by andiwand** [comment] 2023-01-24 10:19
hm for me it is still crashing even with 2 events

this is my geant version:

```
**************************************************************
 Geant4 version Name: geant4-11-00-patch-01 [MT]   (8-March-2022)
                       Copyright : Geant4 Collaboration
                      References : NIM A 506 (2003), 250-303
                                 : IEEE-TNS 53 (2006), 270-278
                                 : NIM A 835 (2016), 186-225
                             WWW : http://geant4.org/
**************************************************************
```

but feel free to close the ticket since it works for both of you now

**Comment by Corentin-Allaire** [comment] 2023-01-24 10:20
@andiwand did you keep the number of thread to 1 ?

**Comment by Corentin-Allaire** [comment] 2023-01-24 10:22
I realised I modified the preselection to cut on x,y and z so I removed that change but it still works on 5 events for now. 
I do have a slightly more recent G4 version :
```**************************************************************
 Geant4 version Name: geant4-11-00-patch-03 [MT]   (16-September-2022)
                       Copyright : Geant4 Collaboration
                      References : NIM A 506 (2003), 250-303
                                 : IEEE-TNS 53 (2006), 270-278
                                 : NIM A 835 (2016), 186-225
                             WWW : http://geant4.org/
**************************************************************```

**Comment by andiwand** [comment] 2023-01-24 10:22
yeah exactly I did't modify the script. just executed the one you sent here https://github.com/acts-project/acts/issues/1578#issuecomment-1401645240

**Comment by benjaminhuth** [comment] 2023-01-24 10:23
So I have `geant4-11-00-patch-03` as well, and for me it also works now with 5 events.
Maybe its indeed the geant version?

**Comment by andiwand** [comment] 2023-01-24 10:24
let me update and check again

**Comment by Corentin-Allaire** [comment] 2023-01-24 10:24
I remember reading there was some issue with patch 01 witch is why I updated the first time I run into the odd segfault

**Comment by Corentin-Allaire** [comment] 2023-01-24 10:25
Let me also open and MR to solve to let people use G4 with the Odd

**Comment by benjaminhuth** [comment] 2023-01-24 10:27
Actually I think this is a good workaround, though not 100% satisfying...

I just wonder if the change in the `full_chain_odd.py` is enough to kind of document this for others?

**Comment by Corentin-Allaire** [comment] 2023-01-24 10:28
In my opinion this is a pythia issue and not an acts one

**Comment by andiwand** [comment] 2023-01-24 14:01
I recompiled G4 with `11.1.0` and it seems not to crash anymore

**Comment by Corentin-Allaire** [comment] 2023-01-24 14:03
I am in the process of running on 100 events just to check that we don't get particles with X or Y > 10m

**Comment by Corentin-Allaire** [comment] 2023-01-25 14:09
I had the simulation run for 100 ttbar events and no issue occurred. I think we can close this one then ! 
As a summary in case someone comes back here :
- Pythia sometime generate particles outside the detector world volume (in particular in Z), using a ParticleSelector can resolve the issue. If the issue was to come back, we might need to extend the ParticleSelector to also cut in X and Y.
- G4 simulation cannot be run in multithreaded mode in Acts, doing so will result in crashes.
- G4 version anterior to `geant4-11-00-patch-03` might also result is segfault when running the simulation (has been shown for version geant4-11-00-patch-01 at least). In case of crashed in G4 try to upgrade to the latest version.

**Closed by Corentin-Allaire** 2023-01-25 14:09 UTC
Labels: Bug
