### ISSUE TITLE
CKF Misses Hits in Seed's Volume

### ISSUE THREAD

**Issue by kkrizka** [acts-project/acts#926] opened 2021-08-04 15:16 UTC
While working on the ACTS tracking for the Muon Colllider, I noticed that the fitted tracks only had one hit in the vertex detector. The one hit corresponded to the layer for which the seed parameters fed to CKF corresponds to. I believe I managed to reproduce this in ACTS v10.0.0 just by following the example commands for the Generic detector.

Is this expected or am I just misinterpreting the results? I also tried with a very generous CKF Chi2 max =10000, but that only picked up hits in the strips detector.

To reproduce:
```shell
../build/bin/ActsExampleFatrasGeneric --output-dir=data/sim_generic/single_muon_barrel --output-csv --events=10000 --bf-constant-tesla=0:0:2 --gen-eta -1:1
../build/bin/ActsExampleCKFTracksGeneric --input-dir data/sim_generic/single_muon_barrel --bf-constant-tesla=0:0:2     --ckf-selection-chi2max 15 --ckf-selection-nmax 10 --output-dir data/ckf_generic/single_muon --digi-config-file ../Examples/Algorithms/Digitization/share/default-smearing-config-generic.json --geo-selection-config-file ../Examples/Algorithms/TrackFinding/share/geoSelection-genericDetector.json
```

This uses volumes 7,8,9 for the seeding. They correspond to the pixel subdetector in the Generic detector. I've added a map of the volumes for reference.

![volumes](https://user-images.githubusercontent.com/177068/128206093-953f3b9e-1f2c-4542-a400-e2b1e5e447ab.png)

Below is a plot showing the average number of hits in each volume per track. Since the single muons are restricted to barrel only, I would expect volumes 8, 13, 17 to have 4, 4, 2 hits on average. This corresponds to a hit in each layer of each subdetector. This is true for 12 and 17. But volume 8 (pixel) ony has a bit more an 1. Far from the expected 4.

Script used to make this plot: [plot.py](https://github.com/acts-project/acts/files/6932299/plot.txt)

![avghitspervolume](https://user-images.githubusercontent.com/177068/128206087-08f0a6e6-12b5-4507-9804-57d5bdafbcc8.png)

I've also attached a `--loglevel 0` run of the CKF example program for the first event.

[event0ckf.txt](https://github.com/acts-project/acts/files/6932289/event0ckf.txt)

If I am interpreting the output correctly, it also picks up only a single hit in the pixel detector. 
```
# grep 'Entering propagation\|Measurement surface' event0ckf.txt 
07:42:11    TrackFinding   VERBOSE   Entering propagation.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=8|lay=2|sen=105 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=2|sen=382 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=4|sen=479 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=6|sen=667 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=8|sen=770 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=17|lay=2|sen=787 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=17|lay=2|sen=786 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=17|lay=4|sen=845 detected.
07:42:11    TrackFinding   VERBOSE   Entering propagation.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=8|lay=2|sen=105 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=2|sen=382 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=4|sen=479 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=6|sen=667 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=8|sen=770 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=17|lay=2|sen=787 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=17|lay=2|sen=786 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=17|lay=4|sen=845 detected.
07:42:11    TrackFinding   VERBOSE   Entering propagation.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=8|lay=4|sen=209 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=8|lay=4|sen=210 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=2|sen=382 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=4|sen=479 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=6|sen=667 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=8|sen=770 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=17|lay=2|sen=787 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=17|lay=2|sen=786 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=17|lay=4|sen=845 detected.
07:42:11    TrackFinding   VERBOSE   Entering propagation.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=8|lay=4|sen=210 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=2|sen=382 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=4|sen=479 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=6|sen=667 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=13|lay=8|sen=770 detected.
07:42:11    TrackFinding   VERBOSE   Measurement surface vol=17|lay=2|sen=786 detected.
```

Event display for the event from the log is below.

![event0](https://user-images.githubusercontent.com/177068/128206091-66b0d1b5-6dc8-4272-ab8b-37553fae99a5.png)

![event0_zoom](https://user-images.githubusercontent.com/177068/128206090-63829ed4-311e-4b86-9b78-e2f8ef033ee4.png)

**Comment by gagnonlg** [comment] 2021-08-19 22:33
#946 may be relevant

**Comment by XiaocongAi** [comment] 2021-08-22 22:53
Hi @kkrizka , thank you for the detailed info. I could repeat this issue successfully. I guess this might be related to the way how the navigator works, i.e. if the starting parameters is on a pixel layer, the navigator will skip the searching for additional layers in this volume hence the other pixel layers will never be walked through. That's probably why we see that the search for measurements on other pixel layers is not even triggered.
@asalzburger should have some insight into this.

**Comment by kkrizka** [comment] 2021-09-08 15:39
Hi @asalzburger, any idea what could be wrong? To me, this seems like a serious bug in ACTS.

**Comment by gagnonlg** [comment] 2021-09-09 15:32
Added the "Impact - Major" label, to hopefully attract more attention to this issue

**Comment by asalzburger** [comment] 2021-09-14 15:47
This looks like a navigation problem - @XiaocongAi will provide some more information.

**Comment by XiaocongAi** [comment] 2021-09-15 12:52
Hi @asalzburger , I made a summary of the issue with an example here:
[NavigationIssue.pdf](https://github.com/acts-project/acts/files/7170147/NavigationIssue.pdf)

Could you have a look to see how we can fix the issue?

**Comment by asalzburger** [comment] 2021-09-16 07:22
Excellent @XiaocongAi  - I will get right onto it.

**Comment by asalzburger** [comment] 2021-09-16 14:40
```shell
./ActsExampleFatrasGeneric --output-dir=data/sim_generic_const2Tesla/single_muon --output-csv --gen-nparticles 100 --gen-mom-gev 0.4:100 --gen-eta -2.5:2.5 --select-pt-gev=0.4: --fatras-pmin-gev 0.4 --bf-constant-tesla=0:0:2 --events=1

./ActsExampleCKFTracksGeneric --input-dir=data/sim_generic_const2Tesla/single_muon --output-dir=data/reco_generic_const2Tesla/single_muon --bf-constant-tesla=0:0:2 --digi-config-file ../../Examples/Algorithms/Digitization/share/default-smearing-config-generic.json --geo-selection-config-file ../../Examples/Algorithms/TrackFinding/share/geoSelection-genericDetector.json -l 0 > log_single_muon_ckf.txt
```

**Comment by asalzburger** [comment] 2021-09-16 14:40
Thanks @XiaocongAi - I will give it a try.

**Comment by asalzburger** [comment] 2021-09-17 07:39
Alright, I can reproduce the problem:

```shell
09:25:36    TrackFinding   VERBOSE   Detected passive surface: vol=8|lay=2|apr=2
09:25:36    TrackFinding   VERBOSE   Creating Hole track state with tip = 2
09:25:36    TrackFinding   VERBOSE   Material effects on surface: vol=8|lay=2|apr=2 at update stage: 0 are :
09:25:36    TrackFinding   VERBOSE   eLoss = 0.00116798, variancePhi = 1.69586e-06, varianceTheta = 2.49965e-07, varianceQoverP = 2.56719e-11
09:25:36    TrackFinding   VERBOSE   Target: 0 | Target stepSize (path limit) updated to ( +∞,  +∞, 25293.1,  +∞ )
09:25:36    TrackFinding   VERBOSE   Pixel::Barrel | Entering navigator::target.
09:25:36    TrackFinding   VERBOSE   Pixel::Barrel | Try to find boundaries, we are at:  -35.5098 -0.320236   85.3151, dir:   -0.383881 -0.00571219    0.923365
09:25:36    TrackFinding   VERBOSE   Finding compatibleBoundaries
09:25:36    TrackFinding   VERBOSE   Volume reports 4 boundary surfaces
09:25:36    TrackFinding   VERBOSE   Processing boundaries
```

The navigation is finished with layer 2 in volume 8 and jumps directly to the boundaries ... bad .

**Comment by asalzburger** [comment] 2021-09-17 08:08
More diagnostics:

The starting layer is correctly handled, however, since there was a fast navigation initialisation - the `navLayer` vector is empty - and hence the target mode is automatically set to `targetBoundaries`. A simple check on the `startLayer` condition could fix this indeed.

**Comment by asalzburger** [comment] 2021-09-17 08:56
Looks like this did the trick:

```shell
10:53:49    TrackFinding   VERBOSE   Intersection: state is ON SURFACE
10:53:49    TrackFinding   VERBOSE   Pixel::Barrel | Status Surface successfully hit, storing it.
10:53:49    TrackFinding   VERBOSE   Pixel::Barrel | Current surface set to surface vol=8|lay=4|sen=320
```

**Comment by asalzburger** [comment] 2021-09-17 09:01
Hi @kkrizka and @XiaocongAi - see my proposed fix for this issue - could you please confirm/cross-check that this does indeed address the issue?

**Comment by kkrizka** [comment] 2021-09-17 14:07
HI @asalzburger and @XiaocongAi ,

Thank you very much for looking into this and providing a fix!

I also confirm that the proposed fix seems to work. Here is the hits per track plot from my original report with the fix applied. Around 4 hits in volume 8 on average = looks good.

![avghitspervolume](https://user-images.githubusercontent.com/177068/133796323-c381c9e2-99ed-4807-8f60-12f6022900d5.png)

**Comment by asalzburger** [comment] 2021-09-17 14:20
Ok, waiting for @XiaocongAi 's approval - then we can merge that in.

**Closed** 2021-09-17 22:12 UTC
Labels: Bug, Component - Core, Component - Examples, Impact - Major
