### ISSUE TITLE
ML Ambi python level test throws FPE *sometimes*

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/acts#2023] opened 2023-04-12 07:35 UTC
This unfortunately does not seem to be fully deterministic.

See: https://github.com/acts-project/acts/actions/runs/4673301747/jobs/8276745945

Any ideas @Corentin-Allaire?

**Comment by benjaminhuth** [comment] 2023-04-12 07:41
Just a rough idea without looking into the error or the code: Could it be that an rng inside ONNX is not seeded properly?

**Comment by Corentin-Allaire** [comment] 2023-04-12 08:34
Just to be sure FPE means that it is the job that failed not that the test didn't return the correct value. Right ?

**Comment by Corentin-Allaire** [comment] 2023-04-12 09:37
My guess is that it is somehow related to #2005 but since it passed the CI I am not sure how... What seem to be happening is that we overflow in Onnx, that as probably something to do with data preparation. Maybe we do not always load the model properly ? (I don't see why but that could be an issue)

**Comment by benjaminhuth** [comment] 2023-04-12 10:20
Another potential source of this problem could be uninitialized memory somewhere in the input data? Again, just guessing, not having tested anything.

**Comment by paulgessinger** [comment] 2023-04-12 11:43
> Just to be sure FPE means that it is the job that failed not that the test didn't return the correct value. Right ?

Exactly, @Corentin-Allaire

**Comment by Corentin-Allaire** [comment] 2023-04-12 11:50
Just to be sure could anybody have a look at the line in the test : https://github.com/acts-project/acts/blob/6e3571201557050fbe6938f4f1c2ebf2de93fb14/Examples/Python/tests/test_examples.py#L1234#L1267

Does this looks correct to you ? I am asking because it seems like the code work outside the test

**Comment by paulgessinger** [comment] 2023-04-12 11:53
I guess the problem is that the FPE is not reproducible. So for some reason, the CI runs into a an edge case where some FP operation is invalid.

**Comment by Corentin-Allaire** [comment] 2023-04-12 12:27
What surprise me is that even if it is not reproducible if we run this on a lot of events the error should appear again no ?

**Comment by benjaminhuth** [comment] 2023-04-12 12:29
Not sure if this would happen in any case... If it is a uninitialized memory bug for example, then I would expect it to appear independently of the number of events, but more dependent on the preconditions in memory...

**Comment by Corentin-Allaire** [comment] 2023-04-12 12:40
> Not sure if this would happen in any case... If it is a uninitialized memory bug for example, then I would expect it to appear independently of the number of events, but more dependent on the preconditions in memory...

In that case maybe it has nothing to do with the solver itself and it is just related to calling `full_chain_odd.py` twice in the test ?

**Comment by paulgessinger** [comment] 2023-04-12 13:06
Currently it's using subprocesses to call the script, so the memory should be completely isolated.

**Comment by Corentin-Allaire** [comment] 2023-04-12 13:15
> Currently it's using subprocesses to call the script, so the memory should be completely isolated.

I understood the following lines (at the start of the log) as meaning the we had already defined the geometry variable. Which would mean the memory isn't isolated. But maybe I am misunderstanding something ?
```
Evaluator        WARN  +++ Overwriting variable: name=DetType_TRACKER value= 0x1   Evaluator::Object : existing variable [setVariable error]
Evaluator        WARN  +++ Overwriting variable: name=DetType_CALORIMETER value= 0x2   Evaluator::Object : existing variable [setVariable error]
Evaluator        WARN  +++ Overwriting variable: name=DetType_CHERENKOV value= 0x4   Evaluator::Object : existing variable [setVariable error]
```

**Comment by paulgessinger** [comment] 2023-04-12 13:32
This happens if any of the DD4hep based jobs fail. I'm not entirely sure how that triggers in this case. Any idea @andiwand?

**Comment by Corentin-Allaire** [comment] 2023-04-12 13:49
> Ah I think it's because the test builds the DD4hep geometry before calling the subprocess, and that's not cleaned up then.

Ah this make sense ! But then I have no idea what could be happening, it is in a subprocess so it shouldn't be memory based testing on a large number of event locally doesn't lead to the same issue so it is not fully random. 

So it is maybe something internal to ONNX (and we cannot do anything about it). Any other idea ?

**Comment by andiwand** [comment] 2023-04-12 14:08
yeah exactly if one of the dd4hep tests fails all of them do because the geometry is not cleaned up and for whatever reason you are only allowed to have one material with the same name in G4 :boom:

**Comment by Corentin-Allaire** [comment] 2023-04-12 14:30
I am going to try something in  #2026. The only possible issue I see in the code is that at some point we divide by the ndf of a track. If it was 0 that could be an issue...

**Comment by Corentin-Allaire** [comment] 2023-04-17 11:44
So after some test, I can confirm this is internal to the ONNX inference. I don't have the FPE testing on my mac so I am trying to test this on another computer to see if I can pinpoint exactly where this occur.

**Comment by paulgessinger** [comment] 2023-04-17 15:07
macOS FPE is very tricky unfortunately. 

If you determine it's from code outside of our control, we can disable the FPE check for the test. 

This would be easiest if the test was "inline", so directly in the Python test function rather than being called as a subprocess. Can we simplify the test do run inside the test function without subprocess?

Otherwise, we might need a way to suppress the FPE monitoring that is on by default in the full chain script.

**Comment by Corentin-Allaire** [comment] 2023-04-17 15:12
I am trying to get a docker image working on my ubuntu machine, I would prefer to understand what is happening before doing anything else (maybe the weight of the network are just messed up). Right now the test is just a hash test on the output of the odd_full_chain with the ML solver I can try to think about how to change this.

**Comment by Corentin-Allaire** [comment] 2023-04-20 15:08
Now that https://github.com/acts-project/acts/pull/2026 has been merged in this issue should be resolved. Sorry for the inconvenience !

**Closed by Corentin-Allaire** 2023-04-20 15:09 UTC
